### ISSUE TITLE
Doesn't build with the latest .net and Visual studio

### ISSUE THREAD

**Issue by D-Bullock** [nbarbettini/SimpleTokenProvider#1]
Hi,

Visual studio is claiming that various references don't support the framework (DNX 4.5.1)

**Comment by nbarbettini** [comment]
`dnx451` has been deprecated in .NET Core RC2. Have you updated to the latest [.NET Core SDK](https://www.microsoft.com/net/core)?

**Comment by D-Bullock** [comment]
You're entirely correct, sorry. 
Nothing wrong with your code!
