### ISSUE TITLE
Managing Users

### ISSUE THREAD

**Issue by marticrespi** [nbarbettini/SimpleTokenProvider#12]
Hi, I 've found this solution today. Thanks for sharing!

I have tested all including it in my solution and works well with sample user data, but how can manage for new users? In ASP.NET 4.x new users are stored in a sql express database, what is the best way to can store data users in this case? The same with UserManager validating credentials?

Many thanks.

**Comment by nbarbettini** [comment]
Hi @marticrespi - just a heads up, I'll be out of town on vacation so I won't have a chance to answer any questions here. I'll be happy to take a look at this when I get back.
