### ISSUE TITLE
Store jwt in cookies?

### ISSUE THREAD

**Issue by SamJost** [nbarbettini/SimpleTokenProvider#17]
Is it possible to store the jwt in cookies (with httponly and secure both true), to prevent Cross Site Scripting (XSS) attacks?

**Comment by nbarbettini** [comment]
Yep! It's important to understand the tradeoffs, but that is one approach I've worked on in the [Stormpath libraries](https://github.com/stormpath/stormpath-aspnetcore) that I maintain. There's some discussion on how to achieve this in the article: https://stormpath.com/blog/token-authentication-asp-net-core#validating-tokens-in-asp-net-core

**Comment by ayhamclickandgrow** [comment]
Hi, 
is it possible to use both Cookies AND Headers for Authentication? 
I'm creating an API which i want to use headers, and an admin section where i would like to use cookies.

**Comment by nbarbettini** [comment]
@ayhamclickandgrow Sure, it's possible. Whether the token gets to your application via an HTTP or via cookies (which are just a special case of HTTP headers), you can handle the incoming request appropriately. However, see my previous message about the tradeoffs. It's important to understand how to keep tokens secure.
