### ISSUE TITLE
signalr example?

### ISSUE THREAD

**Issue by Jacknq** [nbarbettini/SimpleTokenProvider#20]
Hi, 
I,m trying to make it work, with signalr authorize attribute on method and your simple token provider, but unfortunately it doesnt work. 
could you maybe provide example, how to do it. 
To me is not clear where you get token from header or url and how its get encrypted?
Thanks

**Comment by nbarbettini** [comment]
I don't have a sample using SignalR, sorry. I'm not familiar enough with SignalR at the moment to offer any advice there.

> To me is not clear where you get token from header or url and how its get encrypted?

You can transmit tokens from the client/browser to the server in a cookie (HttpOnly, Secure), or in a header like `Authorization: Bearer eyJ...`. Tokens are *not* encrypted, only encoded. The signature prevents it from being modified, but it's very important to use HTTPS for all connections.

**Comment by Jacknq** [comment]
Ok, thanks, I customized some saples that I found to make it work. I had to make one class CustomBearerEvents that derives IJwtBearerEvents. I ll populate this in my samples later. Thanks.
