### ISSUE TITLE
.net core 2 compatibility

### ISSUE THREAD

**Issue by Jacknq** [nbarbettini/SimpleTokenProvider#28]
Please add example for .net core 2

**Comment by emiliano84** [comment]
@nbarbettini Do you plane to update this repo to asp.net core 2 (2.2)?

**Comment by Panda-Sharp** [comment]
> Please add example for .net core 2

you can find something here :)

https://developer.okta.com/blog/2018/03/23/token-authentication-aspnetcore-complete-guide

and here:

https://stackoverflow.com/questions/29048122/token-based-authentication-in-asp-net-core
