### ISSUE TITLE
Using TokenProvider with ASP.NET Core Identity

### ISSUE THREAD

**Issue by miker1423** [nbarbettini/SimpleTokenProvider#3]
Hello, Im having trouble with the token provider, basically what i want to do is to manage all the user login and registering with the Identity package of ASP.NET but I want to make my own custom tokens, following your tutorial was great to understand the concept but now Im having trouble with this mixing of auth services, is it possible to do it these way? the error Im getting is "No authentication handler is configured to handle the scheme: Identity.Application", how can I solve it?

**Comment by osya** [comment]
I am trying to implement token-based authentication based on Angular 2 & ASP.NET Core & SimpleTokenProvider. And the same error appears: "InvalidOperationException: No authentication handler is configured to handle the scheme: Identity.Application". Have you any suggestions? I suppose this issue should be reopened

**Comment by miker1423** [comment]
Hello @osya, I remember I solved it my self but I don't remember where the error was, can you share where it fails so I can compare with my code and help you?

**Comment by sicollins** [comment]
Could be a number of reasons so hard to say without seeing some of your code.

Check your Startup.Configure(...) method and make sure that: app.UseIdentity(); appears before app.UserMvc() - the order it very important.

Next ensure you have AutomaticChallenge = true set in your CookieAuthenticationOptions in startup.cs

**Comment by osya** [comment]
Hello, @miker1423, @sicollins . At the moment all my issues with SimpleTokenProvider I already solved. I implemented simple JWT authentication app based on Angular 2.X at client side and ASP.NET Core & SimpleTokenProvider at server side (https://github.com/osya/ASPNetCoreAngular2YoExample). I dont' remember how I fix the error "No authentication handler is configured to handle the scheme: Identity.Application". Thanks
PS: @sicollins , I don't use Cookies in this project

**Comment by sicollins** [comment]
Looking at your github repo https://github.com/osya/ASPNetCoreAngular2YoExample/blob/master/Startup.cs

Try moving app.UseIdentity(); before the ConfigureAuth() call. As I said in my previous post the order in this case is very important.

**Comment by osya** [comment]
@sicollins , thanks. It is fixed.. All works.
