### ISSUE TITLE
Urgent : Sliding Expiration for the cookie?

### ISSUE THREAD

**Issue by shivawahi** [nbarbettini/SimpleTokenProvider#31]
I have read some of the old issues and figured that you have left the task to create HTTPOnly cookie for the user.  This is how I'm creating my cookie in the code:
`  CookieOptions options = new CookieOptions();

                options.Expires = DateTime.Now.AddDays(1);
                options.Secure = false; // Should be True for Production
                options.HttpOnly = true;     
                options.Path = "/";
                Response.Cookies.Append("access_token", "any value", options);`

No, how do I set the sliding expiration of this cookie? Since this cookie is not created by the .Net framework itself, the settings we have mentioned on Startup file doesn't apply for this cookie. Here is teh setting I have done in the Startup file of my .net core 2.0 application.

`services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(option =>

            {
                option.AccessDeniedPath = "/api/Account/Login"; 
                option.ExpireTimeSpan = TimeSpan.FromMinutes(30);
                option.Cookie.Name = "access_token";
                option.LoginPath = "/api/Account/Login";
                option.LogoutPath = "/api/Account/Logout";
                option.SlidingExpiration = true;
                option.Cookie.HttpOnly = true;
                option.Cookie.SameSite = SameSiteMode.None;
                option.TicketDataFormat = new CustomJwtDataFormat(SecurityAlgorithms.HmacSha256, tokenValidationParameters);
            `});

I have set SlidingExpiration to true here but it obviously has no effect on the cookie (containing JWT token) that I have created within my controller.

Can you please help me here?

**Comment by nbarbettini** [comment]
A "sliding" expiration would need to be an absolute expiration date that continually is updated by the server. I don't know for sure, but my guess is that this is how the AddCookie middleware is doing it under the hood.

In the context of ASP.NET Core 2.0, I would not recommend using my SimpleTokenProvider middleware. I've left it up for educational purposes only. If you need to generate JWTs I'd highly recommend [OpenIddict](https://github.com/openiddict/openiddict-core).

**Comment by shivawahi** [comment]
Did you mean on every server request, change the Expires property of CookieOptions and set the cookie again with the same name?

**Comment by nbarbettini** [comment]
Yes, something like: https://stackoverflow.com/a/26006746/3191599

If it were me, I wouldn't roll this functionality myself. I'd use the stock AddCookies middleware + OpenIddict.

**Comment by shivawahi** [comment]
Ok.. thanks for the quick reply.. I appreciate your help on this
