### ISSUE TITLE
Refresh Token option with .NET Core 2 Compatibility

### ISSUE THREAD

**Issue by xts-velkumars** [nbarbettini/SimpleTokenProvider#33]
How do i implement refresh token with  .NET Core 2 Compatibility?

**Comment by nbarbettini** [comment]
I'd recommend [OpenIddict](https://github.com/openiddict/openiddict-core) for this. There is a [refresh token flow](https://github.com/openiddict/openiddict-samples/tree/dev/samples/RefreshFlow) sample you can look at. 👍
