### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by janhartmann** [nbarbettini/SimpleTokenProvider#4]
Forgive me if I am doing something wrong, but by applying your code, I end of having an "Invalid Signature" according to https://jwt.io:

The access token:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJURVNUIiwianRpIjoiODZkMGIxZGItMTQ1Zi00ZWE4LWJkOTYtZmZiNWRkNGQ2NmNiIiwiaWF0IjoxNDY4MDYzMTI0LCJuYmYiOjE0NjgwNjMxMjQsImV4cCI6MTQ2ODA2MzQyNCwiaXNzIjoiVGVzdElzc3VlciIsImF1ZCI6IlRlc3RBdWRpZW5jZSJ9.Wg9G2C43x4ui9AHCtKoOOsmfQlHl80YgzGmC_H-9qkY
```

Gives an invalid signature by validation the token on https://jwt.io? :-)

**Comment by nbarbettini** [comment]
Hey Jan!

Can you show how you are hooking up the middleware? I'd need to see an example of what key you are signing with in order to figure out why the signature is invalid. (Feel free to use a dummy key instead of your real one)

**Comment by janhartmann** [comment]
Hi again,

I figured it out, I misspelled the secret key during validation - sorry for the inconvenience! :)
