### ISSUE TITLE
Can't read Form data from HttpContext

### ISSUE THREAD

**Issue by sicollins** [nbarbettini/SimpleTokenProvider#5]
Thanks for this great repo and article!

I've hit an issue implementing this into my project though and not sure where the issue is stemming from (worth noting I'm using RC2 version of Core: 1.0.0-rc2-3002702 ).

I've set code up exactly as in your Git Repo but have hit problems in the middleware code and not entirely sure what is causing the problem.

So with Content-Type: application/x-www-form-urlencoded

I post to /api/token and all good. The code gets inside private async Task GenerateToken(HttpContext context) but then blows up.

context.Request.Form["username"] throws an exception and returns HTTP Error 502.3 - Bad Gateway.

Form = '((Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest)((Microsoft.AspNetCore.Http.DefaultHttpContext)context).Request).Form' threw an exception of type 'System.MissingMethodException'

Changed Content-Type: multipart/form-data, but this too throws different exception:

Form = '((Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest)((Microsoft.AspNetCore.Http.DefaultHttpContext)context).Request).Form' threw an exception of type 'System.IO.InvalidDataException'

So there would appear to be something fundamentally wrong with either the set up of my WebApi or it's a bug in RC2.

Worth noting the WebAPi is working just fine with 'application/json', PUT, POST, GET, DELETE verbs etc all work fine.

Can anyone help?

**Comment by sicollins** [comment]
Closing this.

My issue was caused by a bug in RC2 - after full upgrade to Core 1.0.0 Preview 2 SDK it all worked.

Shocking...

**Comment by nbarbettini** [comment]
Hey @sicollins - sorry I couldn't reply to this earlier. It's been a busy week!

Glad you got your problem fixed. I've seen a few other issues from the RC2->RTM transition so that's not too surprising.

Cheers!
